/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/submerged-era-e46a97e8ffff454f90ca5c5535e89090
Title: Submerged Era
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[10.145, 18.454, -1.849]} rotation={[-0.307, 0.022, 1.025]} scale={[0.431, 1, 1]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.big_ben} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.outline_black} />
          </group>
          <group position={[12.733, 18.17, -0.268]} rotation={[0, 0, 1.403]} scale={[0.463, 1.074, 1.57]}>
            <mesh geometry={nodes.Object_9.geometry} material={materials.big_ben} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.outline_black} />
          </group>
          <group position={[37.561, -9.745, 6.005]} rotation={[-0.411, 0.989, -0.767]} scale={9.474}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.big_ben} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.outline} />
          </group>
          <group position={[-0.807, 3.317, -2.706]} rotation={[-1.461, 0.462, 0.192]}>
            <group position={[0, 0, -1.787]}>
              <mesh geometry={nodes.Object_30.geometry} material={materials.bot_head} />
              <mesh geometry={nodes.Object_31.geometry} material={materials.outline} />
            </group>
            <group position={[0, 0, -1.787]}>
              <mesh geometry={nodes.Object_33.geometry} material={materials.bot_head} />
              <mesh geometry={nodes.Object_34.geometry} material={materials.outline} />
            </group>
            <group position={[0, 0, -1.787]}>
              <mesh geometry={nodes.Object_36.geometry} material={materials.bot_head} />
              <mesh geometry={nodes.Object_37.geometry} material={materials.outline} />
            </group>
            <group position={[0, 2.329, -4.116]}>
              <mesh geometry={nodes.Object_39.geometry} material={materials.bot_head} />
              <mesh geometry={nodes.Object_40.geometry} material={materials.outline} />
            </group>
            <group position={[0.037, 7.805, -4.558]}>
              <mesh geometry={nodes.Object_42.geometry} material={materials.bot_head} />
              <mesh geometry={nodes.Object_43.geometry} material={materials.outline} />
            </group>
            <mesh geometry={nodes.Object_25.geometry} material={materials.bot_head} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.outline} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.bot_head} position={[0, 0, -1.787]} />
          </group>
          <group position={[20.53, 9.646, 11.539]} rotation={[-2.074, 1.374, 1.843]} scale={0.444}>
            <mesh geometry={nodes.Object_365.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_366.geometry} material={materials['Material.007']} />
          </group>
          <group position={[18.673, 10.338, 16.056]} rotation={[1.068, -1.374, 1.298]} scale={[-0.5, 0.5, 0.5]}>
            <mesh geometry={nodes.Object_368.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_369.geometry} material={materials['Material.007']} />
          </group>
          <group position={[1.377, 11.426, 15.089]} rotation={[2.755, 0.345, -2.817]} scale={[-0.604, 0.604, 0.604]}>
            <mesh geometry={nodes.Object_371.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_372.geometry} material={materials['Material.007']} />
          </group>
          <group position={[15.542, 12.019, 21.176]} rotation={[2.95, -0.455, -2.988]} scale={[-0.246, 0.246, 0.246]}>
            <mesh geometry={nodes.Object_374.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_375.geometry} material={materials['Material.007']} />
          </group>
          <group position={[19.749, 8.45, -4.512]} rotation={[0.186, -0.959, 0.363]} scale={[-0.604, 0.604, 0.604]}>
            <mesh geometry={nodes.Object_377.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_378.geometry} material={materials['Material.007']} />
          </group>
          <group position={[18.928, 9.622, 9.678]} rotation={[0.248, -0.726, 0.413]} scale={[-0.299, 0.299, 0.299]}>
            <mesh geometry={nodes.Object_380.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_381.geometry} material={materials['Material.007']} />
          </group>
          <group position={[17.633, 9.386, 20.883]} rotation={[2.259, -1.354, 2.509]} scale={[-0.228, 0.228, 0.228]}>
            <mesh geometry={nodes.Object_383.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_384.geometry} material={materials['Material.007']} />
          </group>
          <group position={[-2.447, 10.67, 9.944]} rotation={[3.006, 0.354, -2.754]} scale={[-0.335, 0.335, 0.335]}>
            <mesh geometry={nodes.Object_386.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_387.geometry} material={materials['Material.007']} />
          </group>
          <group position={[-2.39, 11.592, 7.394]} rotation={[2.445, 0.655, -1.897]} scale={[-0.165, 0.165, 0.165]}>
            <mesh geometry={nodes.Object_389.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_390.geometry} material={materials['Material.007']} />
          </group>
          <group position={[-1.46, 9.235, 14.719]} rotation={[-2.974, 0.057, -0.28]} scale={0.228}>
            <mesh geometry={nodes.Object_392.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_393.geometry} material={materials['Material.007']} />
          </group>
          <group position={[17.746, 10.94, 7.908]} rotation={[2.599, -1.373, 2.873]} scale={[-0.187, 0.187, 0.187]}>
            <mesh geometry={nodes.Object_395.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_396.geometry} material={materials['Material.007']} />
          </group>
          <group position={[3.656, 12.795, -10.508]} rotation={[-0.142, 1.155, 0.307]} scale={0.457}>
            <mesh geometry={nodes.Object_398.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_399.geometry} material={materials['Material.007']} />
          </group>
          <group position={[6.077, 11.289, -12.308]} rotation={[2.356, -1.259, 2.625]} scale={[-0.238, 0.238, 0.238]}>
            <mesh geometry={nodes.Object_401.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_402.geometry} material={materials['Material.007']} />
          </group>
          <group position={[4.878, 11.451, -5.712]} rotation={[0.551, -1.044, 0.587]} scale={[-0.433, 0.433, 0.433]}>
            <mesh geometry={nodes.Object_404.geometry} material={materials.fish} />
            <mesh geometry={nodes.Object_405.geometry} material={materials['Material.007']} />
          </group>
          <group position={[11.933, 24.162, 8.188]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_541.geometry} material={materials.dude} />
            <mesh geometry={nodes.Object_542.geometry} material={materials.outline_black} />
          </group>
          <group position={[8.221, 21.446, 6.388]} rotation={[-0.666, 0.401, -0.362]}>
            <mesh geometry={nodes.Object_544.geometry} material={materials.boat} />
            <mesh geometry={nodes.Object_545.geometry} material={materials.outline} />
          </group>
          <group position={[11.799, 17.522, -1.509]} rotation={[-Math.PI, 1.544, -Math.PI]} scale={0.358}>
            <mesh geometry={nodes.Object_547.geometry} material={materials.boat} />
            <mesh geometry={nodes.Object_548.geometry} material={materials.outline} />
          </group>
          <group position={[11.799, 17.503, -1.509]} rotation={[-Math.PI, 1.544, -Math.PI]} scale={0.358}>
            <mesh geometry={nodes.Object_550.geometry} material={materials.boat} />
            <mesh geometry={nodes.Object_551.geometry} material={materials.outline} />
          </group>
          <group position={[11.799, 17.363, -1.509]} rotation={[-Math.PI, 1.544, -Math.PI]} scale={0.358}>
            <mesh geometry={nodes.Object_553.geometry} material={materials.boat} />
            <mesh geometry={nodes.Object_554.geometry} material={materials.outline} />
          </group>
          <group position={[1.904, 14.103, -24.997]} rotation={[0.308, 0.033, -0.532]}>
            <mesh geometry={nodes.Object_636.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_637.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-9.331, 13.364, -20.41]} rotation={[0.59, 1.076, -3.087]}>
            <mesh geometry={nodes.Object_639.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_640.geometry} material={materials['outline.001']} />
          </group>
          <group position={[6.429, 8.412, -24.143]} rotation={[0.162, -0.349, -0.818]}>
            <mesh geometry={nodes.Object_642.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_643.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-16.914, 9.045, -20.941]} rotation={[-0.1, 0.967, -2.439]}>
            <mesh geometry={nodes.Object_645.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_646.geometry} material={materials['outline.001']} />
          </group>
          <group position={[22.243, 8.641, -27.334]} rotation={[-Math.PI, 0.609, -Math.PI]}>
            <mesh geometry={nodes.Object_650.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_651.geometry} material={materials.outline_semi_transparent} />
          </group>
          <group position={[-4.947, 5.861, 15.521]}>
            <mesh geometry={nodes.Object_653.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_654.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-14.69, 4.508, -7.527]} rotation={[2.279, 0.875, 2.89]} scale={0.545}>
            <mesh geometry={nodes.Object_656.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_657.geometry} material={materials['outline.001']} />
          </group>
          <group position={[35.935, 1.732, -9.76]} rotation={[0.2, 0.27, -0.008]} scale={0.414}>
            <mesh geometry={nodes.Object_659.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_660.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-14.826, -7.365, 14.848]} rotation={[2.83, 0.889, -0.167]} scale={1.246}>
            <mesh geometry={nodes.Object_662.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_663.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-6.84, -5.717, 16.664]} rotation={[2.805, 0.101, 0.077]} scale={1.246}>
            <mesh geometry={nodes.Object_665.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_666.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-23.009, -5.723, 7.343]} rotation={[-3.112, 0.596, 0.539]} scale={1.763}>
            <mesh geometry={nodes.Object_668.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_669.geometry} material={materials['outline.001']} />
          </group>
          <group position={[1.089, 0.435, 30.666]} rotation={[0.561, -0.079, 0.244]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Object_671.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_672.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-16.258, 6.525, -26.733]} rotation={[-0.079, 0.403, -1.983]} scale={1.174}>
            <mesh geometry={nodes.Object_676.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_677.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-10.388, 8.068, -8.28]} rotation={[1.777, 0.325, 2.836]} scale={0.743}>
            <mesh geometry={nodes.Object_679.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_680.geometry} material={materials['outline.001']} />
          </group>
          <group position={[42.543, 3.284, -15.383]} rotation={[0.199, 0.142, -0.008]} scale={0.257}>
            <mesh geometry={nodes.Object_684.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_685.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-20.797, 7.902, -30.976]} rotation={[0.768, 0.665, 2.766]} scale={1.136}>
            <mesh geometry={nodes.Object_687.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_688.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-25.349, 1.865, -18.031]} rotation={[0.442, 0.497, 1.955]} scale={1.123}>
            <mesh geometry={nodes.Object_690.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_691.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-12.322, -2.458, 27.259]} rotation={[0.586, 0.039, 0.366]} scale={1.185}>
            <mesh geometry={nodes.Object_693.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_694.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-29.152, -7.592, -4.731]} rotation={[1.884, 0.991, 1.258]} scale={1.763}>
            <mesh geometry={nodes.Object_696.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_697.geometry} material={materials['outline.001']} />
          </group>
          <group position={[1.61, -1.065, -37.894]} rotation={[0.484, -0.04, -2.911]} scale={1.136}>
            <mesh geometry={nodes.Object_699.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_700.geometry} material={materials['outline.001']} />
          </group>
          <group position={[-3.141, 0.221, -43.356]} rotation={[0.652, 0.49, 3.094]} scale={[-1.136, 1.136, 1.136]}>
            <mesh geometry={nodes.Object_702.geometry} material={materials['grass_2.001']} />
            <mesh geometry={nodes.Object_703.geometry} material={materials['outline.001']} />
          </group>
          <group position={[6.696, 18.022, 11.735]} rotation={[-0.168, -0.102, 0.138]}>
            <mesh geometry={nodes.Object_725.geometry} material={materials.water} />
            <mesh geometry={nodes.Object_726.geometry} material={materials.boat} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials['water.001']} position={[6.851, 18.341, 12.578]} rotation={[-0.984, -0.228, 0.499]} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Material} position={[52.938, 7.701, -26.031]} rotation={[-1.404, -0.67, -0.819]} scale={[0.169, 1.701, 0.169]} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Material} position={[53.579, 6.703, -26.146]} rotation={[-2.017, -0.605, -0.966]} scale={[0.169, 1.701, 0.169]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Material} position={[52.407, 6.806, -27.252]} rotation={[-1.76, -0.862, -0.548]} scale={[0.169, 1.701, 0.169]} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Material} position={[53.546, 7.017, -24.014]} rotation={[-1.404, -0.67, -0.819]} scale={[0.169, 1.701, 0.169]} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Material} position={[47.279, 3.679, -4.871]} rotation={[-1.367, -0.523, -0.994]} scale={[0.169, 1.701, 0.169]} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.bubles_bright} position={[35.962, 5.838, -38.591]} rotation={[-0.058, -0.256, -0.956]} scale={0.364} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.bubles_bright} position={[33.873, 4.595, -35.495]} rotation={[-1.039, 0.819, -0.614]} scale={0.557} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.bubles_bright} position={[36.461, 7.364, -35.08]} rotation={[-2.991, 0.511, 0.877]} scale={0.568} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.bubles_bright} position={[37.527, 10.524, -38.017]} rotation={[-2.794, 0.686, 0.766]} scale={0.451} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.bubles_bright} position={[38.456, 6.829, -42.743]} rotation={[-3.003, 0.497, 0.883]} scale={0.078} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.bubles_bright} position={[36.334, 10.909, -44.676]} rotation={[-0.222, -0.02, -0.979]} scale={0.322} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.bubles_bright} position={[37.156, 6.74, -48.13]} rotation={[-1.394, 0.938, -0.339]} scale={0.201} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.bubles_bright} position={[34.472, 9.907, -32.555]} rotation={[-2.164, 0.948, 0.295]} scale={0.124} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.bubles_bright} position={[34.651, 6.876, -28.972]} rotation={[2.96, 0.079, 0.977]} scale={0.361} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.bubles_bright} position={[33.889, 14.971, -36.335]} rotation={[-0.213, -0.033, -0.978]} scale={0.274} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.bubles_bright} position={[35.655, 3.293, -18.431]} rotation={[-3.11, 0.036, 2.882]} scale={0.364} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.bubles_bright} position={[35.178, 1.945, -22.099]} rotation={[-1.737, -0.249, 3.057]} scale={0.557} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.bubles_bright} position={[35.099, 5.692, -21.404]} rotation={[-0.278, -0.115, -2.905]} scale={0.568} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.bubles_bright} position={[37.46, 7.927, -18.374]} rotation={[-0.513, -0.167, -2.938]} scale={0.451} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.bubles_bright} position={[36.06, 4.406, -13.631]} rotation={[-0.261, -0.111, -2.903]} scale={0.078} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.bubles_bright} position={[40.823, 5.711, -12.925]} rotation={[-2.833, -0.038, 2.882]} scale={0.322} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.bubles_bright} position={[38.745, 2.111, -9.36]} rotation={[-1.475, -0.262, 3.124]} scale={0.201} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.bubles_bright} position={[37.223, 7.117, -24.606]} rotation={[-1.015, -0.244, -3.043]} scale={0.124} />
          <mesh geometry={nodes.Object_81.geometry} material={materials.bubles_bright} position={[33.883, 5.895, -27.673]} rotation={[0.24, 0.02, -2.88]} scale={0.361} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.bubles_bright} position={[42.231, 9.584, -21.589]} rotation={[-2.848, -0.034, 2.881]} scale={0.274} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.bubles_bright} position={[27.709, 9.217, -4.829]} rotation={[-2.833, 0.716, 1.496]} scale={0.262} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.bubles_bright} position={[33.195, 8.788, -8.125]} rotation={[-2.927, -0.669, 1.499]} scale={0.401} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.bubles_bright} position={[28.011, 10.767, -10.918]} rotation={[0.355, -1.034, -1.46]} scale={0.409} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.bubles_bright} position={[22.684, 14.72, -8.014]} rotation={[0.442, -1.27, -1.38]} scale={0.324} />
          <mesh geometry={nodes.Object_93.geometry} material={materials.bubles_bright} position={[21.236, 9.055, -0.036]} rotation={[0.351, -1.016, -1.464]} scale={0.056} />
          <mesh geometry={nodes.Object_95.geometry} material={materials.bubles_bright} position={[20.188, 16.687, 2.56]} rotation={[-2.856, 0.43, 1.509]} scale={0.232} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.bubles_bright} position={[19.948, 10.326, 8.813]} rotation={[-2.957, -0.923, 1.477]} scale={0.145} />
          <mesh geometry={nodes.Object_99.geometry} material={materials.bubles_bright} position={[30.419, 15.749, -14.656]} rotation={[3.131, -1.362, 1.295]} scale={0.089} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.bubles_bright} position={[34.338, 10.983, -19.183]} rotation={[0.291, -0.501, -1.506]} scale={0.26} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.bubles_bright} position={[22.023, 14.596, -10.369]} rotation={[-2.855, 0.446, 1.508]} scale={0.197} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.bubles_bright} position={[19.781, 5.477, -40.454]} rotation={[-2.833, 0.716, 1.496]} scale={0.262} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.bubles_bright} position={[25.266, 5.048, -43.75]} rotation={[-2.927, -0.669, 1.499]} scale={0.401} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.bubles_bright} position={[20.082, 7.027, -46.543]} rotation={[0.355, -1.034, -1.46]} scale={0.409} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.bubles_bright} position={[14.755, 10.981, -43.639]} rotation={[0.442, -1.27, -1.38]} scale={0.324} />
          <mesh geometry={nodes.Object_113.geometry} material={materials.bubles_bright} position={[13.307, 5.316, -35.66]} rotation={[0.351, -1.016, -1.464]} scale={0.056} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.bubles_bright} position={[12.259, 12.947, -33.065]} rotation={[-2.856, 0.43, 1.509]} scale={0.232} />
          <mesh geometry={nodes.Object_117.geometry} material={materials.bubles_bright} position={[12.019, 6.586, -26.812]} rotation={[-2.957, -0.923, 1.477]} scale={0.145} />
          <mesh geometry={nodes.Object_119.geometry} material={materials.bubles_bright} position={[22.49, 12.009, -50.281]} rotation={[3.131, -1.362, 1.295]} scale={0.089} />
          <mesh geometry={nodes.Object_121.geometry} material={materials.bubles_bright} position={[26.41, 7.243, -54.807]} rotation={[0.291, -0.501, -1.506]} scale={0.26} />
          <mesh geometry={nodes.Object_123.geometry} material={materials.bubles_bright} position={[17.604, 20.022, -45.939]} rotation={[-2.855, 0.446, 1.508]} scale={0.197} />
          <mesh geometry={nodes.Object_125.geometry} material={materials.bubles_bright} position={[22.495, 5.69, -45.558]} rotation={[-2.739, 1.106, 1.328]} scale={0.143} />
          <mesh geometry={nodes.Object_127.geometry} material={materials.bubles_bright} position={[27.981, 5.261, -48.854]} rotation={[-2.987, -0.268, 1.459]} scale={0.219} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.bubles_bright} position={[22.797, 7.24, -51.647]} rotation={[0.86, -1.4, -0.888]} scale={0.223} />
          <mesh geometry={nodes.Object_131.geometry} material={materials.bubles_bright} position={[17.47, 11.194, -48.743]} rotation={[2.531, -1.42, 0.77]} scale={0.177} />
          <mesh geometry={nodes.Object_133.geometry} material={materials.bubles_bright} position={[16.022, 5.529, -40.764]} rotation={[0.799, -1.385, -0.948]} scale={0.031} />
          <mesh geometry={nodes.Object_135.geometry} material={materials.bubles_bright} position={[14.974, 13.16, -38.169]} rotation={[-2.84, 0.825, 1.412]} scale={0.127} />
          <mesh geometry={nodes.Object_137.geometry} material={materials.bubles_bright} position={[14.734, 6.799, -31.916]} rotation={[-3.019, -0.521, 1.447]} scale={0.079} />
          <mesh geometry={nodes.Object_139.geometry} material={materials.bubles_bright} position={[25.205, 12.222, -55.385]} rotation={[-3.112, -0.961, 1.382]} scale={0.049} />
          <mesh geometry={nodes.Object_141.geometry} material={materials.bubles_bright} position={[29.124, 7.456, -59.911]} rotation={[0.32, -0.896, -1.398]} scale={0.142} />
          <mesh geometry={nodes.Object_143.geometry} material={materials.bubles_bright} position={[20.319, 20.235, -51.043]} rotation={[-2.836, 0.841, 1.409]} scale={0.108} />
          <mesh geometry={nodes.Object_145.geometry} material={materials.bubles_bright} position={[23.062, 0.928, 16.329]} rotation={[-2.84, -0.867, 1.794]} scale={0.17} />
          <mesh geometry={nodes.Object_147.geometry} material={materials.bubles_bright} position={[28.302, 0.528, 12.652]} rotation={[-0.04, -0.862, -1.793]} scale={0.26} />
          <mesh geometry={nodes.Object_149.geometry} material={materials.bubles_bright} position={[22.922, 2.479, 10.235]} rotation={[0.22, 0.554, -1.74]} scale={0.265} />
          <mesh geometry={nodes.Object_151.geometry} material={materials.bubles_bright} position={[17.793, 6.403, 13.511]} rotation={[0.178, 0.319, -1.722]} scale={0.211} />
          <mesh geometry={nodes.Object_153.geometry} material={materials.bubles_bright} position={[16.947, 0.732, 21.571]} rotation={[0.223, 0.572, -1.742]} scale={0.036} />
          <mesh geometry={nodes.Object_155.geometry} material={materials.bubles_bright} position={[16.044, 8.358, 24.235]} rotation={[-2.688, -1.143, 1.923]} scale={0.15} />
          <mesh geometry={nodes.Object_157.geometry} material={materials.bubles_bright} position={[16.284, 1.996, 30.488]} rotation={[0.028, -0.612, -1.747]} scale={0.094} />
          <mesh geometry={nodes.Object_159.geometry} material={materials.bubles_bright} position={[25.031, 7.473, 6.336]} rotation={[0.105, -0.173, -1.717]} scale={0.058} />
          <mesh geometry={nodes.Object_161.geometry} material={materials.bubles_bright} position={[28.645, 2.728, 1.542]} rotation={[0.401, 1.075, -1.877]} scale={0.169} />
          <mesh geometry={nodes.Object_163.geometry} material={materials.bubles_bright} position={[20.422, 15.46, 11.016]} rotation={[-2.701, -1.128, 1.912]} scale={0.128} />
          <mesh geometry={nodes.Object_165.geometry} material={materials.bubles_bright} position={[22.262, -2.958, 18.026]} rotation={[-2.767, -0.968, 1.526]} scale={0.17} />
          <mesh geometry={nodes.Object_167.geometry} material={materials.bubles_bright} position={[27.234, -1.325, 14.316]} rotation={[0.437, -0.785, -1.535]} scale={0.26} />
          <mesh geometry={nodes.Object_169.geometry} material={materials.bubles_bright} position={[21.444, 0.163, 12.626]} rotation={[0.392, 0.649, -1.539]} scale={0.265} />
          <mesh geometry={nodes.Object_171.geometry} material={materials.bubles_bright} position={[15.929, 1.984, 16.95]} rotation={[0.401, 0.411, -1.543]} scale={0.211} />
          <mesh geometry={nodes.Object_173.geometry} material={materials.bubles_bright} position={[16.641, -5.749, 23.077]} rotation={[0.392, 0.667, -1.539]} scale={0.036} />
          <mesh geometry={nodes.Object_175.geometry} material={materials.bubles_bright} position={[14.577, 0.527, 27.811]} rotation={[-2.807, -1.255, 1.489]} scale={0.15} />
          <mesh geometry={nodes.Object_177.geometry} material={materials.bubles_bright} position={[16.358, -7.15, 31.994]} rotation={[0.426, -0.531, -1.541]} scale={0.094} />
          <mesh geometry={nodes.Object_179.geometry} material={materials.bubles_bright} position={[22.368, 6.346, 10.279]} rotation={[0.414, -0.085, -1.545]} scale={0.058} />
          <mesh geometry={nodes.Object_181.geometry} material={materials.bubles_bright} position={[26.441, 3.886, 4.285]} rotation={[0.35, 1.183, -1.504]} scale={0.169} />
          <mesh geometry={nodes.Object_183.geometry} material={materials.bubles_bright} position={[16.735, 11.704, 17.097]} rotation={[-2.803, -1.239, 1.493]} scale={0.128} />
          <mesh geometry={nodes.Object_185.geometry} material={materials.bubles_bright} position={[39.849, -18.285, -63.928]} rotation={[-2.767, -0.968, 1.526]} scale={0.17} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.bubles_bright} position={[44.821, -16.653, -67.638]} rotation={[0.437, -0.785, -1.535]} scale={0.26} />
          <mesh geometry={nodes.Object_189.geometry} material={materials.bubles_bright} position={[39.031, -15.165, -69.328]} rotation={[0.392, 0.649, -1.539]} scale={0.265} />
          <mesh geometry={nodes.Object_191.geometry} material={materials.bubles_bright} position={[33.516, -13.344, -65.003]} rotation={[0.401, 0.411, -1.543]} scale={0.211} />
          <mesh geometry={nodes.Object_193.geometry} material={materials.bubles_bright} position={[34.228, -21.077, -58.877]} rotation={[0.392, 0.667, -1.539]} scale={0.036} />
          <mesh geometry={nodes.Object_195.geometry} material={materials.bubles_bright} position={[32.164, -14.8, -54.143]} rotation={[-2.807, -1.255, 1.489]} scale={0.15} />
          <mesh geometry={nodes.Object_197.geometry} material={materials.bubles_bright} position={[33.945, -22.478, -49.959]} rotation={[0.426, -0.531, -1.541]} scale={0.094} />
          <mesh geometry={nodes.Object_199.geometry} material={materials.bubles_bright} position={[39.955, -8.982, -71.675]} rotation={[0.414, -0.085, -1.545]} scale={0.058} />
          <mesh geometry={nodes.Object_201.geometry} material={materials.bubles_bright} position={[44.028, -11.442, -77.668]} rotation={[0.35, 1.183, -1.504]} scale={0.169} />
          <mesh geometry={nodes.Object_203.geometry} material={materials.bubles_bright} position={[34.322, -3.623, -64.857]} rotation={[-2.803, -1.239, 1.493]} scale={0.128} />
          <mesh geometry={nodes.Object_205.geometry} material={materials.bubles_bright} position={[2.593, 0.852, -43.764]} rotation={[-1.82, 1.233, 0.198]} scale={0.17} />
          <mesh geometry={nodes.Object_207.geometry} material={materials.bubles_bright} position={[1.332, 0.545, -37.483]} rotation={[3.139, 0.108, 1.238]} scale={0.26} />
          <mesh geometry={nodes.Object_209.geometry} material={materials.bubles_bright} position={[6.597, 3.157, -39.495]} rotation={[2.199, -1.159, 0.625]} scale={0.265} />
          <mesh geometry={nodes.Object_211.geometry} material={materials.bubles_bright} position={[7.567, 6.994, -45.558]} rotation={[2.554, -0.988, 0.94]} scale={0.211} />
          <mesh geometry={nodes.Object_213.geometry} material={materials.bubles_bright} position={[3.516, 0.436, -51.757]} rotation={[2.162, -1.169, 0.591]} scale={0.036} />
          <mesh geometry={nodes.Object_215.geometry} material={materials.bubles_bright} position={[1.329, 7.714, -54.639]} rotation={[-2.463, 1.09, 0.793]} scale={0.15} />
          <mesh geometry={nodes.Object_217.geometry} material={materials.bubles_bright} position={[-2.196, 0.622, -58.75]} rotation={[3.056, -0.133, 1.237]} scale={0.094} />
          <mesh geometry={nodes.Object_219.geometry} material={materials.bubles_bright} position={[7.017, 8.437, -35.428]} rotation={[2.89, -0.55, 1.18]} scale={0.058} />
          <mesh geometry={nodes.Object_221.geometry} material={materials.bubles_bright} position={[8.282, 4.084, -29.263]} rotation={[0.799, -1.138, -0.685]} scale={0.169} />
          <mesh geometry={nodes.Object_223.geometry} material={materials.bubles_bright} position={[6.108, 16.083, -42.331]} rotation={[-2.438, 1.101, 0.771]} scale={0.128} />
          <mesh geometry={nodes.Object_225.geometry} material={materials.bubles_bright} position={[-0.09, 0.782, -46.075]} rotation={[-2.197, 1.057, 0.64]} scale={0.17} />
          <mesh geometry={nodes.Object_227.geometry} material={materials.bubles_bright} position={[0.193, 0.255, -39.689]} rotation={[-3.116, -0.13, 1.162]} scale={0.26} />
          <mesh geometry={nodes.Object_229.geometry} material={materials.bubles_bright} position={[4.624, 3.325, -42.777]} rotation={[1.638, -1.166, -0.014]} scale={0.265} />
          <mesh geometry={nodes.Object_231.geometry} material={materials.bubles_bright} position={[3.845, 7.342, -48.751]} rotation={[2.194, -1.107, 0.493]} scale={0.211} />
          <mesh geometry={nodes.Object_233.geometry} material={materials.bubles_bright} position={[-1.052, 0.593, -54.071]} rotation={[1.593, -1.165, -0.055]} scale={0.036} />
          <mesh geometry={nodes.Object_235.geometry} material={materials.bubles_bright} position={[-4.397, 7.722, -56.087]} rotation={[-2.548, 0.851, 0.93]} scale={0.15} />
          <mesh geometry={nodes.Object_237.geometry} material={materials.bubles_bright} position={[-8.251, 0.444, -59.523]} rotation={[3.06, -0.363, 1.136]} scale={0.094} />
          <mesh geometry={nodes.Object_239.geometry} material={materials.bubles_bright} position={[5.595, 8.544, -38.726]} rotation={[2.808, -0.755, 0.999]} scale={0.058} />
          <mesh geometry={nodes.Object_241.geometry} material={materials.bubles_bright} position={[8.602, 4.193, -33.195]} rotation={[0.663, -0.908, -0.876]} scale={0.169} />
          <mesh geometry={nodes.Object_243.geometry} material={materials.bubles_bright} position={[2.512, 16.219, -44.932]} rotation={[-2.533, 0.864, 0.919]} scale={0.128} />
          <mesh geometry={nodes.Object_245.geometry} material={materials.bubles_bright} position={[19.313, 7.239, -7.325]} rotation={[-1.657, 0.912, 0.723]} scale={0.13} />
          <mesh geometry={nodes.Object_247.geometry} material={materials.bubles_bright} position={[19.555, 6.836, -5.934]} rotation={[-2.524, -0.257, 1.076]} scale={0.198} />
          <mesh geometry={nodes.Object_249.geometry} material={materials.bubles_bright} position={[20.351, 7.849, -6.536]} rotation={[1.999, -1.072, -0.288]} scale={0.202} />
          <mesh geometry={nodes.Object_251.geometry} material={materials.bubles_bright} position={[19.871, 8.978, -7.65]} rotation={[2.507, -1.087, 0.162]} scale={0.161} />
          <mesh geometry={nodes.Object_253.geometry} material={materials.bubles_bright} position={[18.907, 7.531, -9.101]} rotation={[1.963, -1.066, -0.319]} scale={0.028} />
          <mesh geometry={nodes.Object_255.geometry} material={materials.bubles_bright} position={[17.827, 9.046, -9.136]} rotation={[-1.938, 0.7, 0.927]} scale={0.115} />
          <mesh geometry={nodes.Object_257.geometry} material={materials.bubles_bright} position={[17.165, 7.439, -10.21]} rotation={[-2.659, -0.478, 1.028]} scale={0.072} />
          <mesh geometry={nodes.Object_259.geometry} material={materials.bubles_bright} position={[20.464, 8.848, -5.384]} rotation={[-2.998, -0.837, 0.816]} scale={0.044} />
          <mesh geometry={nodes.Object_261.geometry} material={materials.bubles_bright} position={[21.445, 7.764, -4.42]} rotation={[1.262, -0.756, -0.888]} scale={0.129} />
          <mesh geometry={nodes.Object_263.geometry} material={materials.bubles_bright} position={[19.317, 10.691, -6.329]} rotation={[-1.926, 0.712, 0.919]} scale={0.098} />
          <mesh geometry={nodes.Object_265.geometry} material={materials.cherry} position={[-34.822, 42.886, -32.928]} rotation={[1.48, 0.405, 2.858]} scale={3.876} />
          <mesh geometry={nodes.Object_267.geometry} material={materials.cherry} position={[-36.536, 40.199, -33.173]} rotation={[-2.28, -0.026, 3.137]} scale={0.434} />
          <mesh geometry={nodes.Object_269.geometry} material={materials.cherry} position={[-33.005, 43.644, -31.959]} rotation={[1.558, 0.376, -2.898]} scale={5.151} />
          <mesh geometry={nodes.Object_271.geometry} material={materials.cherry} position={[-21.928, 42.182, -27.292]} rotation={[-0.908, -0.157, 2.863]} scale={1.581} />
          <mesh geometry={nodes.Object_273.geometry} material={materials.cherry} position={[-18.183, 44.515, -23.925]} rotation={[1.63, -0.267, -2.081]} scale={4.684} />
          <mesh geometry={nodes.Object_275.geometry} material={materials.cherry} position={[-20.683, 41.297, -25.602]} rotation={[-1.267, 0.154, 2.735]} scale={5.41} />
          <mesh geometry={nodes.Object_277.geometry} material={materials.cherry} position={[-0.422, 37.277, -13.75]} rotation={[1.425, -0.538, 2.559]} scale={1.906} />
          <mesh geometry={nodes.Object_279.geometry} material={materials.cherry} position={[-6.032, 36.421, -12.77]} rotation={[3.014, 0.593, 2.742]} scale={2.031} />
          <mesh geometry={nodes.Object_281.geometry} material={materials.cherry} position={[-8.647, 35.338, -17.878]} rotation={[-1.593, 0.611, 1.992]} scale={2.181} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.cherry} position={[5.685, 32.417, -5.443]} rotation={[1.333, -0.448, 2.297]} scale={4.023} />
          <mesh geometry={nodes.Object_285.geometry} material={materials.cherry} position={[3.093, 33.037, -7.263]} rotation={[2.08, -0.004, -3.036]} scale={5.119} />
          <mesh geometry={nodes.Object_287.geometry} material={materials.cherry} position={[-0.213, 34.748, -8.995]} rotation={[2.311, 0.128, 3.096]} scale={0.598} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.cherry} position={[7.112, 27.467, -10.613]} rotation={[-0.436, -0.382, -2.179]} scale={3.119} />
          <mesh geometry={nodes.Object_291.geometry} material={materials.cherry} position={[5.498, 30.247, -12.058]} rotation={[-0.117, -0.512, 2.163]} scale={3.744} />
          <mesh geometry={nodes.Object_293.geometry} material={materials.cherry} position={[2.822, 33.298, -13.89]} rotation={[0.193, -0.61, 2.6]} scale={4.037} />
          <mesh geometry={nodes.Object_295.geometry} material={materials.cherry} position={[7.613, 30.732, -9.515]} rotation={[0.748, -0.612, 2.646]} scale={0.031} />
          <mesh geometry={nodes.Object_297.geometry} material={materials.cherry} position={[10.554, 30.127, -3.543]} rotation={[1.539, -0.151, -2.57]} scale={3.462} />
          <mesh geometry={nodes.Object_299.geometry} material={materials.cherry} position={[7.527, 30.654, -4.526]} rotation={[1.822, -0.08, 2.921]} scale={4.475} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.cherry} position={[12.582, 30.376, -1.797]} rotation={[1.7, 0.037, 2.631]} scale={1.122} />
          <mesh geometry={nodes.Object_303.geometry} material={materials.cherry} position={[9.273, 29.663, -1.872]} rotation={[2.011, 0.132, 2.825]} scale={2.178} />
          <mesh geometry={nodes.Object_305.geometry} material={materials.cherry} position={[4.818, 24.975, -3.832]} rotation={[-2.297, 0.638, 2.927]} scale={2.868} />
          <mesh geometry={nodes.Object_307.geometry} material={materials.cherry} position={[13.492, 25.33, -6.436]} rotation={[-0.464, -0.413, -2.679]} scale={3.462} />
          <mesh geometry={nodes.Object_309.geometry} material={materials.cherry} position={[11.386, 29.626, -5.316]} rotation={[1.017, -0.41, -2.986]} scale={2.202} />
          <mesh geometry={nodes.Object_311.geometry} material={materials.cherry} position={[17.814, 32.096, -3.184]} rotation={[1.211, -0.189, 2.455]} scale={5.429} />
          <mesh geometry={nodes.Object_313.geometry} material={materials.cherry} position={[33.92, 36.042, -4.543]} rotation={[1.055, -0.186, -2.548]} scale={2.056} />
          <mesh geometry={nodes.Object_315.geometry} material={materials.cherry} position={[23.712, 32.339, 0.526]} rotation={[2.451, 0.412, -1.994]} scale={1.598} />
          <mesh geometry={nodes.Object_317.geometry} material={materials.cherry} position={[14.51, 29.322, 0.88]} rotation={[2.711, 0.48, 2.766]} scale={1.934} />
          <mesh geometry={nodes.Object_319.geometry} material={materials.cherry} position={[29.996, 32.451, 1.006]} rotation={[2.623, 0.458, -2.247]} scale={0.192} />
          <mesh geometry={nodes.Object_321.geometry} material={materials.cherry} position={[22.4, 29.719, 1.63]} rotation={[2.909, 0.516, 2.089]} scale={0.936} />
          <mesh geometry={nodes.Object_323.geometry} material={materials.cherry} position={[13.878, 27.076, 0.83]} rotation={[-3.052, 0.557, 2.189]} scale={3.115} />
          <mesh geometry={nodes.Object_325.geometry} material={materials.cherry} position={[25.836, 24.538, -1.557]} rotation={[-2.051, 0.366, 3.011]} scale={2.96} />
          <mesh geometry={nodes.Object_327.geometry} material={materials.cherry} position={[21.856, 24.645, -4.467]} rotation={[-1.136, -0.111, -2.961]} scale={5.382} />
          <mesh geometry={nodes.Object_329.geometry} material={materials.cherry} position={[16.432, 24.579, -4.844]} rotation={[-0.891, -0.238, 2.242]} scale={0.589} />
          <mesh geometry={nodes.Object_331.geometry} material={materials.cherry} position={[27.354, 25.676, -7.379]} rotation={[-0.935, -0.234, -2.53]} scale={1.718} />
          <mesh geometry={nodes.Object_333.geometry} material={materials.cherry} position={[23.326, 26.645, -7.321]} rotation={[-0.676, -0.345, 2.237]} scale={1.824} />
          <mesh geometry={nodes.Object_335.geometry} material={materials.cherry} position={[17.151, 27.112, -6.169]} rotation={[-0.988, -0.793, -2.26]} scale={4.284} />
          <mesh geometry={nodes.Object_337.geometry} material={materials.cherry} position={[29.662, 28.497, -9.622]} rotation={[-0.499, -0.41, -1.967]} scale={2.522} />
          <mesh geometry={nodes.Object_339.geometry} material={materials.cherry} position={[24.975, 29.536, -8.971]} rotation={[-0.22, -0.462, -2.309]} scale={1.794} />
          <mesh geometry={nodes.Object_341.geometry} material={materials.cherry} position={[17.53, 26.46, -5.694]} rotation={[-0.423, -0.427, -2.512]} scale={2.168} />
          <mesh geometry={nodes.Object_343.geometry} material={materials.cherry} position={[33.463, 34.473, -7.703]} rotation={[0.438, -0.406, -2.113]} scale={2.537} />
          <mesh geometry={nodes.Object_345.geometry} material={materials.cherry} position={[40.606, 34.103, 10.045]} rotation={[1.981, 0.291, 1.941]} scale={4.234} />
          <mesh geometry={nodes.Object_347.geometry} material={materials.cherry} position={[32.015, 28.782, 3.238]} rotation={[3.059, 0.531, -2.944]} scale={3.465} />
          <mesh geometry={nodes.Object_349.geometry} material={materials.cherry} position={[38.947, 27.111, 13.815]} rotation={[2.901, 0.551, -2.992]} scale={1.353} />
          <mesh geometry={nodes.Object_351.geometry} material={materials.cherry} position={[33.453, 24.498, 3.938]} rotation={[-2.466, 0.502, 2.861]} scale={4.562} />
          <mesh geometry={nodes.Object_353.geometry} material={materials.cherry} position={[33.703, 28.913, -8.533]} rotation={[-0.46, -0.426, -2.882]} scale={5.95} />
          <mesh geometry={nodes.Object_355.geometry} material={materials.cherry} position={[42.557, 30.411, 0.468]} rotation={[-0.099, -0.496, -2.124]} scale={2.132} />
          <mesh geometry={nodes.Object_357.geometry} material={materials.cherry} position={[40.792, 32.842, -1.575]} rotation={[0.218, -0.457, -2.501]} scale={5.317} />
          <mesh geometry={nodes.Object_359.geometry} material={materials.cherry} position={[36.122, 32.047, -7.528]} rotation={[-0.031, -0.466, 2.802]} scale={0.435} />
          <mesh geometry={nodes.Object_361.geometry} material={materials.cherry} position={[44.706, 32.646, 6.471]} rotation={[0.451, -0.421, -2.221]} scale={0.687} />
          <mesh geometry={nodes.Object_363.geometry} material={materials.cherry} position={[42.037, 34.525, 3.641]} rotation={[0.855, -0.27, -2.158]} scale={2.746} />
          <mesh geometry={nodes.Object_407.geometry} material={materials.blue_fish} position={[-5.262, 19.255, -23.834]} rotation={[0.002, 0.198, -0.006]} scale={0.541} />
          <mesh geometry={nodes.Object_409.geometry} material={materials.blue_fish} position={[-12.783, 19.094, -3.697]} rotation={[0.162, 1.339, -0.071]} scale={0.541} />
          <mesh geometry={nodes.Object_411.geometry} material={materials['red_fish.001']} position={[-5.277, 18.473, 4.581]} rotation={[0.036, 1.477, -0.04]} scale={0.762} />
          <mesh geometry={nodes.Object_413.geometry} material={materials['red_fish.001']} position={[28.06, 5.766, -14.137]} rotation={[3.138, -0.306, 3.136]} scale={0.762} />
          <mesh geometry={nodes.Object_415.geometry} material={materials['yellow_ish.002']} position={[-11.599, 18.473, -15.818]} rotation={[3.138, -0.204, -0.005]} scale={0.762} />
          <mesh geometry={nodes.Object_417.geometry} material={materials['yellow_ish.002']} position={[23.852, 18.473, -17.82]} rotation={[3.138, -0.219, -0.006]} scale={0.762} />
          <mesh geometry={nodes.Object_419.geometry} material={materials['yellow_ish.002']} position={[30.801, 18.473, -29.266]} rotation={[3.138, 0.124, -0.004]} scale={[-0.762, 0.762, 0.762]} />
          <mesh geometry={nodes.Object_421.geometry} material={materials['red_fish.002']} position={[-5.277, 18.473, 4.581]} rotation={[0.036, 1.477, -0.04]} scale={0.762} />
          <mesh geometry={nodes.Object_423.geometry} material={materials.foliages} position={[-4.561, 19.084, -34.784]} rotation={[0, -0.552, 0]} scale={45.116} />
          <mesh geometry={nodes.Object_425.geometry} material={materials.foliages} position={[-2.599, 18.666, -29.469]} scale={22.326} />
          <mesh geometry={nodes.Object_427.geometry} material={materials.foliages} position={[39.261, 18.668, -29.233]} rotation={[0, -0.552, 0]} scale={46.883} />
          <mesh geometry={nodes.Object_429.geometry} material={materials.foliages} position={[-10.755, 18.697, -18.621]} scale={27.874} />
          <mesh geometry={nodes.Object_431.geometry} material={materials.foliages} position={[-9.093, 17.548, 6.838]} scale={27.874} />
          <mesh geometry={nodes.Object_433.geometry} material={materials.foliages} position={[-14.537, 18.671, -18.504]} rotation={[-0.003, -1.405, -0.003]} scale={27.874} />
          <mesh geometry={nodes.Object_435.geometry} material={materials.foliages} position={[-14.46, 18.671, -22.269]} rotation={[0, 0, -0.001]} scale={44.651} />
          <mesh geometry={nodes.Object_437.geometry} material={materials.foliages} position={[-10.809, 18.519, -13.765]} scale={17.967} />
          <mesh geometry={nodes.Object_439.geometry} material={materials.foliages} position={[-11.191, 18.671, -23.189]} scale={14.409} />
          <mesh geometry={nodes.Object_441.geometry} material={materials.foliages} position={[-6.046, 18.681, -29.806]} scale={17.239} />
          <mesh geometry={nodes.Object_443.geometry} material={materials.foliages} position={[-9.344, 18.193, 0.031]} rotation={[0, -0.755, 0]} scale={34.97} />
          <mesh geometry={nodes.Object_445.geometry} material={materials.foliages} position={[-5.552, 18.922, -0.003]} rotation={[0, -0.619, -0.001]} scale={27.874} />
          <mesh geometry={nodes.Object_447.geometry} material={materials.foliages} position={[-9.623, 19.046, -15.635]} scale={22.644} />
          <mesh geometry={nodes.Object_449.geometry} material={materials.foliages} position={[-13.756, 18.671, -4.418]} scale={22.644} />
          <mesh geometry={nodes.Object_451.geometry} material={materials.foliages} position={[-13.743, 18.931, -0.429]} rotation={[-0.041, 0, 0]} scale={17.285} />
          <mesh geometry={nodes.Object_453.geometry} material={materials.foliages} position={[-11.529, 18.671, -6.523]} scale={21.188} />
          <mesh geometry={nodes.Object_455.geometry} material={materials.foliages} position={[-13.301, 18.671, -8.687]} rotation={[Math.PI, -1.186, Math.PI]} scale={21.188} />
          <mesh geometry={nodes.Object_457.geometry} material={materials.foliages} position={[-13.323, 18.672, -12.84]} scale={18.77} />
          <mesh geometry={nodes.Object_459.geometry} material={materials.foliages} position={[18.948, 17.457, -6.52]} rotation={[0, 0, -0.001]} scale={27.874} />
          <mesh geometry={nodes.Object_461.geometry} material={materials.foliages} position={[19.669, 17.656, -10.475]} rotation={[0, 0, -0.001]} scale={19.762} />
          <mesh geometry={nodes.Object_463.geometry} material={materials.foliages} position={[26.375, 17.489, -13.895]} rotation={[0, 0, -0.001]} scale={27.874} />
          <mesh geometry={nodes.Object_465.geometry} material={materials.foliages} position={[27.402, 17.652, -19.579]} rotation={[0, 0, -0.001]} scale={22.639} />
          <mesh geometry={nodes.Object_467.geometry} material={materials.foliages} position={[24.323, 17.939, -22.324]} rotation={[2.889, -0.307, 2.985]} scale={36.664} />
          <mesh geometry={nodes.Object_469.geometry} material={materials.foliages} position={[15.514, 18.656, -28.936]} rotation={[0, 0, -0.001]} scale={27.874} />
          <mesh geometry={nodes.Object_471.geometry} material={materials.foliages} position={[16.981, 18.927, -31.465]} rotation={[-0.143, -0.995, -0.232]} scale={27.874} />
          <mesh geometry={nodes.Object_473.geometry} material={materials.foliages} position={[-5.478, 18.667, 7.559]} rotation={[0, 0, -0.001]} scale={19.762} />
          <mesh geometry={nodes.Object_475.geometry} material={materials.foliages} position={[24.883, 16.966, -9.443]} rotation={[-3.141, -1.332, 3.141]} scale={27.874} />
          <mesh geometry={nodes.Object_477.geometry} material={materials.foliages} position={[20.453, 17.655, -8.918]} rotation={[0, 0, -0.001]} scale={16.497} />
          <mesh geometry={nodes.Object_479.geometry} material={materials.foliages} position={[-1.654, 18.736, -36.262]} rotation={[-0.169, -1.295, -0.212]} scale={34.766} />
          <mesh geometry={nodes.Object_481.geometry} material={materials.foliages} position={[21.672, 17.761, -8.947]} rotation={[-1.098, -1.388, -1.171]} scale={10.095} />
          <mesh geometry={nodes.Object_483.geometry} material={materials.foliages} position={[24.476, 17.508, -12.956]} rotation={[2.858, -0.22, 3.055]} scale={20.064} />
          <mesh geometry={nodes.Object_485.geometry} material={materials.foliages} position={[28.336, 17.865, -14.293]} rotation={[-0.264, -0.011, 0.085]} scale={27.874} />
          <mesh geometry={nodes.Object_487.geometry} material={materials.foliages} position={[0.83, 18.674, -32.392]} rotation={[0.027, -0.548, 0.152]} scale={21.209} />
          <mesh geometry={nodes.Object_489.geometry} material={materials.foliages} position={[-2.065, 18.673, -31.796]} rotation={[-0.979, 1.386, 0.987]} scale={25.377} />
          <mesh geometry={nodes.Object_491.geometry} material={materials.foliages} position={[23.873, 17.66, -15.878]} rotation={[0.119, 1.112, -0.247]} scale={27.874} />
          <mesh geometry={nodes.Object_493.geometry} material={materials.foliages} position={[25.504, 17.299, -17.651]} rotation={[-0.102, 0.006, -0.108]} scale={21.483} />
          <mesh geometry={nodes.Object_495.geometry} material={materials.foliages} position={[-10.969, 18.672, -4.43]} rotation={[0, -0.552, -0.001]} scale={8.387} />
          <mesh geometry={nodes.Object_497.geometry} material={materials.foliages} position={[-8.804, 17.686, -20.638]} rotation={[0, 0.349, 0]} scale={7.176} />
          <mesh geometry={nodes.Object_499.geometry} material={materials.foliages} position={[24.483, 16.422, -20.825]} rotation={[-0.021, -0.576, -0.126]} scale={7.131} />
          <mesh geometry={nodes.Object_501.geometry} material={materials.foliages} position={[25.364, 16.497, -19.998]} rotation={[0.168, 1.285, -0.105]} scale={8.633} />
          <mesh geometry={nodes.Object_503.geometry} material={materials.foliages} position={[-11.809, 18.465, -22.055]} rotation={[3.035, 0.934, -3.078]} scale={6.023} />
          <mesh geometry={nodes.Object_505.geometry} material={materials.foliages} position={[-11.868, 17.321, -3.481]} rotation={[-0.009, 0.783, 0.027]} scale={6.502} />
          <mesh geometry={nodes.Object_507.geometry} material={materials.foliages} position={[-8.735, 18.4, -19.985]} rotation={[-2.491, -1.425, -2.609]} scale={9.326} />
          <mesh geometry={nodes.Object_509.geometry} material={materials.foliages} position={[-8.018, 17.214, 2.187]} rotation={[-0.008, -0.314, -0.033]} scale={6.918} />
          <mesh geometry={nodes.Object_511.geometry} material={materials.foliages} position={[-0.142, 19.573, -30.083]} rotation={[-0.015, -0.935, -0.023]} scale={9.167} />
          <mesh geometry={nodes.Object_513.geometry} material={materials.foliages} position={[1.659, 18.363, -30.599]} rotation={[-0.007, 0.212, -0.011]} scale={8.849} />
          <mesh geometry={nodes.Object_515.geometry} material={materials.foliages} position={[1.857, 17.652, -28.519]} rotation={[-0.021, -0.576, -0.126]} scale={8.09} />
          <mesh geometry={nodes.Object_517.geometry} material={materials.foliages} position={[21.1, 16.463, -6.637]} rotation={[3.023, 1.162, -2.976]} scale={9.178} />
          <mesh geometry={nodes.Object_519.geometry} material={materials.foliages} position={[-6.69, 18.571, 1.28]} rotation={[0, -0.552, -0.001]} scale={17.86} />
          <mesh geometry={nodes.Object_521.geometry} material={materials.foliages} position={[-12.462, 18.037, -1.607]} rotation={[1.071, -1.169, 1.137]} scale={8.078} />
          <mesh geometry={nodes.Object_523.geometry} material={materials.foliages} position={[-10.685, 18.776, -4.555]} rotation={[-2.996, -1.023, -2.766]} scale={5.757} />
          <mesh geometry={nodes.Object_525.geometry} material={materials.foliages} position={[37.282, 20.002, -28.845]} rotation={[-2.587, -1.077, -2.738]} scale={20.659} />
          <mesh geometry={nodes.Object_527.geometry} material={materials.foliages} position={[20.314, 17.299, 4.706]} rotation={[-0.102, 0.006, -0.108]} scale={21.483} />
          <mesh geometry={nodes.Object_529.geometry} material={materials.foliages} position={[21.536, 18.649, 4.152]} rotation={[0, 1.224, 0]} scale={13.286} />
          <mesh geometry={nodes.Object_531.geometry} material={materials.foliages} position={[33.252, 18.029, -11.401]} rotation={[-2.875, -0.711, -2.983]} scale={45.116} />
          <mesh geometry={nodes.Object_533.geometry} material={materials.foliages} position={[26.667, 18.18, -21.359]} rotation={[-2.756, -1.062, -2.913]} scale={22.326} />
          <mesh geometry={nodes.Object_535.geometry} material={materials.foliages} position={[6.792, 6.447, -17.979]} rotation={[0.094, 0.257, 2.441]} scale={8.437} />
          <mesh geometry={nodes.Object_537.geometry} material={materials.foliages} position={[6.019, 6.871, -19.522]} rotation={[0.107, 0.137, 2.504]} scale={8.849} />
          <mesh geometry={nodes.Object_539.geometry} material={materials.lineworks} position={[0, -19.899, 0]} />
          <mesh geometry={nodes.Object_556.geometry} material={materials.shadows} position={[38.676, 17.903, -28.177]} rotation={[0, -0.552, 0]} scale={42.432} />
          <mesh geometry={nodes.Object_558.geometry} material={materials.shadows} position={[-5.722, 17.903, -33.867]} rotation={[0, -0.552, 0]} scale={38.681} />
          <mesh geometry={nodes.Object_560.geometry} material={materials.shadows} position={[-1.391, 17.903, -36.385]} rotation={[0, -0.552, 0]} scale={27.358} />
          <mesh geometry={nodes.Object_562.geometry} material={materials.shadows} position={[-2.894, 17.903, -31.834]} rotation={[0, -0.552, 0]} scale={27.358} />
          <mesh geometry={nodes.Object_564.geometry} material={materials.shadows} position={[-1.038, 17.903, -31.216]} rotation={[0, -0.552, 0]} scale={19.822} />
          <mesh geometry={nodes.Object_566.geometry} material={materials.shadows} position={[0.862, 17.903, -31.481]} rotation={[0, -0.552, 0]} scale={11.84} />
          <mesh geometry={nodes.Object_568.geometry} material={materials.shadows} position={[-2.01, 17.903, -29.404]} rotation={[0, -0.552, 0]} scale={[17.656, 17.655, 17.656]} />
          <mesh geometry={nodes.Object_570.geometry} material={materials.shadows} position={[-5.854, 17.903, -29.89]} rotation={[0, -0.552, 0]} scale={[17.656, 17.655, 17.656]} />
          <mesh geometry={nodes.Object_572.geometry} material={materials.shadows} position={[-14.691, 17.903, -21.76]} rotation={[0, -0.552, 0]} scale={29.861} />
          <mesh geometry={nodes.Object_574.geometry} material={materials.shadows} position={[-14.647, 17.903, -18.755]} rotation={[0, -0.552, 0]} scale={29.861} />
          <mesh geometry={nodes.Object_576.geometry} material={materials.shadows} position={[-10.936, 17.903, -18.357]} rotation={[0, -0.552, 0]} scale={23.717} />
          <mesh geometry={nodes.Object_578.geometry} material={materials.shadows} position={[-9.478, 17.903, -15.485]} rotation={[0, -0.552, 0]} scale={23.717} />
          <mesh geometry={nodes.Object_580.geometry} material={materials.shadows} position={[-11.245, 17.903, -13.983]} rotation={[0, -0.552, 0]} scale={19.201} />
          <mesh geometry={nodes.Object_582.geometry} material={materials.shadows} position={[-13.278, 17.903, -12.746]} rotation={[0, -0.552, 0]} scale={21.564} />
          <mesh geometry={nodes.Object_584.geometry} material={materials.shadows} position={[-13.543, 17.903, -9.034]} rotation={[0, -0.552, 0]} scale={21.564} />
          <mesh geometry={nodes.Object_586.geometry} material={materials.shadows} position={[-11.289, 17.903, -6.339]} rotation={[0, -0.552, 0]} scale={18.239} />
          <mesh geometry={nodes.Object_588.geometry} material={materials.shadows} position={[-13.719, 17.903, -3.997]} rotation={[0, -0.552, 0]} scale={19.111} />
          <mesh geometry={nodes.Object_590.geometry} material={materials.shadows} position={[-13.675, 17.015, -0.771]} rotation={[0, -0.552, 0]} scale={19.111} />
          <mesh geometry={nodes.Object_592.geometry} material={materials.shadows} position={[-11.687, 15.899, -3.511]} rotation={[0, -0.552, 0]} scale={10.786} />
          <mesh geometry={nodes.Object_594.geometry} material={materials.shadows} position={[-10.229, 17.015, 0.598]} rotation={[0, -0.552, 0]} scale={26.48} />
          <mesh geometry={nodes.Object_596.geometry} material={materials.shadows} position={[-5.501, 17.015, -0.418]} rotation={[0, -0.552, 0]} scale={22.512} />
          <mesh geometry={nodes.Object_598.geometry} material={materials.shadows} position={[-8.771, 17.015, 6.829]} rotation={[0, -0.552, 0]} scale={22.785} />
          <mesh geometry={nodes.Object_600.geometry} material={materials.shadows} position={[-5.191, 17.015, 7.359]} rotation={[0, -0.552, 0]} scale={15.676} />
          <mesh geometry={nodes.Object_602.geometry} material={materials.shadows} position={[18.934, 17.015, -6.074]} rotation={[0, -0.552, 0]} scale={19.433} />
          <mesh geometry={nodes.Object_604.geometry} material={materials.shadows} position={[24.634, 14.942, -9.034]} rotation={[0, -0.552, 0]} scale={22.962} />
          <mesh geometry={nodes.Object_606.geometry} material={materials.shadows} position={[19.641, 17.015, -10.713]} rotation={[0, -0.552, 0]} scale={15.047} />
          <mesh geometry={nodes.Object_608.geometry} material={materials.shadows} position={[20.702, 17.015, -8.813]} rotation={[0, -0.552, 0]} scale={10.989} />
          <mesh geometry={nodes.Object_610.geometry} material={materials.shadows} position={[20.834, 17.015, -7.267]} rotation={[0, -0.552, 0]} scale={8.356} />
          <mesh geometry={nodes.Object_612.geometry} material={materials.shadows} position={[22.027, 17.015, -8.46]} rotation={[0, -0.552, 0]} scale={10.66} />
          <mesh geometry={nodes.Object_614.geometry} material={materials.shadows} position={[24.502, 17.015, -12.481]} rotation={[0, -0.552, 0]} scale={13.795} />
          <mesh geometry={nodes.Object_616.geometry} material={materials.shadows} position={[26.49, 17.015, -13.585]} rotation={[0, -0.552, 0]} scale={18.904} />
          <mesh geometry={nodes.Object_618.geometry} material={materials.shadows} position={[28.832, 17.015, -14.911]} rotation={[0, -0.552, 0]} scale={25.217} />
          <mesh geometry={nodes.Object_620.geometry} material={materials.shadows} position={[25.783, 17.015, -17.65]} rotation={[0, -0.552, 0]} scale={15.4} />
          <mesh geometry={nodes.Object_622.geometry} material={materials.shadows} position={[24.016, 17.015, -15.397]} rotation={[0, -0.552, 0]} scale={15.4} />
          <mesh geometry={nodes.Object_624.geometry} material={materials.shadows} position={[27.33, 17.015, -19.506]} rotation={[0, -0.552, 0]} scale={15.4} />
          <mesh geometry={nodes.Object_626.geometry} material={materials.shadows} position={[25.209, 17.015, -18.949]} rotation={[0, -0.552, 0]} scale={11.592} />
          <mesh geometry={nodes.Object_628.geometry} material={materials.shadows} position={[23.706, 17.015, -22.351]} rotation={[0, -0.552, 0]} scale={20.649} />
          <mesh geometry={nodes.Object_630.geometry} material={materials.shadows} position={[15.753, 17.015, -29.598]} rotation={[0, -0.552, 0]} scale={20.649} />
          <mesh geometry={nodes.Object_632.geometry} material={materials.shadows} position={[16.813, 17.015, -31.409]} rotation={[0, -0.552, 0]} scale={16.427} />
          <mesh geometry={nodes.Object_634.geometry} material={materials.shadows} position={[31.782, 17.608, -10.971]} rotation={[0, -0.552, 0]} scale={42.432} />
          <mesh geometry={nodes.Object_648.geometry} material={materials['grass_2.001']} position={[0, -9.903, 0]} />
          <mesh geometry={nodes.Object_674.geometry} material={materials['grass_2.001']} position={[5.036, -13.081, -1.746]} rotation={[-0.093, 0.021, -0.155]} />
          <mesh geometry={nodes.Object_682.geometry} material={materials['grass_2.001']} position={[21.843, -37.679, 8.076]} rotation={[-0.608, 0.278, 0.552]} scale={[1.309, 1.226, 1.249]} />
          <mesh geometry={nodes.Object_705.geometry} material={materials.material} rotation={[-Math.PI, 0, 0]} scale={[-398.261, 398.261, 398.261]} />
          <mesh geometry={nodes.Object_707.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Object_709.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Object_711.geometry} material={materials['background.001']} position={[-38.578, -12.883, 5.027]} scale={[2.423, 2.105, 2.423]} />
          <mesh geometry={nodes.Object_713.geometry} material={materials.background} position={[-6.122, 18.506, -0.655]} rotation={[0, 0.073, -0.001]} scale={1.158} />
          <mesh geometry={nodes.Object_715.geometry} material={materials['Material.001']} position={[0.071, -3.489, 7.538]} />
          <mesh geometry={nodes.Object_717.geometry} material={materials.frame} position={[0.001, 18.889, 0]} scale={[0.991, 1, 0.772]} />
          <mesh geometry={nodes.Object_719.geometry} material={materials.frame_alpha} position={[16.634, 18.971, -2.78]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.071, 1.101, 0.833]} />
          <mesh geometry={nodes.Object_721.geometry} material={materials.waves} position={[-1.579, -2.429, -0.729]} rotation={[0.12, -0.026, -0.017]} />
          <mesh geometry={nodes.Object_723.geometry} material={materials.water} position={[6.013, 16.965, 12.603]} rotation={[-0.981, 0.254, -0.128]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
